apiVersion: v1
kind: Pod
metadata:
  name: springvolume
  labels:
    app: animals
    env: prod
spec:
  containers:
  - name: bear
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: animals-persistent-storage
      mountPath: /data/redis
  - name: moose
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: animals-persistent-storage
      mountPath: /app/data
  volumes:
  - name: animals-persistent-storage
    hostPath: 
      path: /tmp/files
